---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-helm-chart-registry
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: harbor
  url: https://harbor.lab.dev/chartrepo/library
  type: helm
  username: admin
  password: Harbor12345
