---
###############################################################################
## Common configuration
###############################################################################
projects:
  development:
    apps:
      petclinic:
        from_registry: True
        chart_path: petclinic
        repo_url: https://github.com/BoulderES/petclinic.git
        target_revision: development
        namespace: petclinic
        values_files:
          - values-development.yaml
