---
###############################################################################
## Common configuration
###############################################################################
argocd:
  url: https://kubernetes.default.svc
  development:
    apps:
      cps-fctc-gsp-frontend:
        enabled: True
environment_values_files: values-environment.yaml
projects:
  development:
    apps:
      petclinic:
        from_registry: True
        chart_path: petclinic
        repo_url: https://github.com/BoulderES/petclinic.git
        target_revision: development
        namespace: petclinic
        values_files:
          - values-development.yaml
