---
argocd:
  url: argocd.lab.dev

git:
  url: https://bitbucket.org

environment_values_files: values-environment.yaml

projects:
  default:
    enabled: true
    destination: https://kubernetes.default.svc
    apps:
      haproxy:
        enabled: true
        from_registry: true
        chart_path: haproxy
        repo_url: https://github.com/BoulderES/argocd.git
        target_revision: main
        namespace: haproxy
      ingress-nginx:
        enabled: true
        from_registry: true
        chart_path: ingress-nginx
        repo_url: https://github.com/BoulderES/argocd.git
        target_revision: main
        namespace: ingress-nginx
      #    values_files:
      #      - values-lab.yaml
      argocd-app:
        enabled: true
        chart_path: argocd-app
        repo_url: https://github.com/BoulderES/argocd.git
        target_revision: main
        namespace: argocd
        ingress:
          - enabled: false
            name: argocd-app
            hosts:
              - name: http
                host: argocd.lab.dev
                path: /
                port: 443
                service_name: argocd-app-default-server
            annotations:
              kubernetes.io/ingress.class: "nginx"
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/backend-protocol: HTTPS
              ingress.kubernetes.io/force-ssl-redirect: "true"
#        syncPolicy:
#          automated:
#            prune: false
#            selfHeal: true

      argocd-config:
        enabled: true
        chart_path: argocd-config
        repo_url: https://github.com/BoulderES/argocd.git
        target_revision: main
        namespace: argocd
        values_files:
          - values-environment.yaml
        syncPolicy:
          automated:
            prune: false
            selfHeal: true

chartrepo:
  harbor:
    enabled: true
    url: https://harbor.lab.dev
    #    url: http://harbor-default-core.harbor.svc.cluster.local

    custom_ca: |
      harbor.lab.dev: |
        -----BEGIN CERTIFICATE-----
        MIIHTDCCBjSgAwIBAgIQQoD3pTIdaKTHjB16erX/CTANBgkqhkiG9w0BAQsFADCB
        jzELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G
        A1UEBxMHU2FsZm9yZDEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQD
        Ey5TZWN0aWdvIFJTQSBEb21haW4gVmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENB
        MB4XDTIyMDcwNzAwMDAwMFoXDTIzMDcwNzIzNTk1OVowIjEgMB4GA1UEAwwXKi5y
        YW5jaGVyLXBvYy51bmljYy5vcmcwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
        IgJ2ApJaAcpQCokmdJeqSUSKSaL7bNoF0zr3IJUaZw48OIKqIybj3VBKEu4TnX6I
        zbAY3ZASmotMP1Vt2JNRfEKnlM9UIMGstBIVaiyE8DnzzFADU3ZYFp5xiIdCFTiU
        wt8qzZopj2nstMYfkhinXqZnhDHyssZAtB48A5YNBfrpAmArdN1hIz9H9wcwmqAe
        WAS0SE3Y6uvyiae0w9llIREopCn6e+zL1jgxVodW4//4VhzwtLgAY73WDzYDC4Ob
        bDKrCxU6UPZJZE21IuT7pERoW61SzhRq03Z87Ak6rRMOuoMyGQIDAQABo4IDDjCC
        AwowHwYDVR0jBBgwFoAUjYxexFStiuF36Zv5mwXhuAGNYeEwHQYDVR0OBBYEFAnS
        7rlyzJV4cOZqiLygl3qJPnPHMA4GA1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAA
        MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBJBgNVHSAEQjBAMDQGCysG
        AQQBsjEBAgIHMCUwIwYIKwYBBQUHAgEWF2h0dHBzOi8vc2VjdGlnby5jb20vQ1BT
        MAgGBmeBDAECATCBhAYIKwYBBQUHAQEEeDB2ME8GCCsGAQUFBzAChkNodHRwOi8v
        Y3J0LnNlY3RpZ28uY29tL1NlY3RpZ29SU0FEb21haW5WYWxpZGF0aW9uU2VjdXJl
        U2VydmVyQ0EuY3J0MCMGCCsGAQUFBzABhhdodHRwOi8vb2NzcC5zZWN0aWdvLmNv
        bTA5BgNVHREEMjAwghcqLnJhbmNoZXItcG9jLnVuaWNjLm9yZ4IVcmFuY2hlci1w
        b2MudW5pY2Mub3JnMIIBfAYKKwYBBAHWeQIEAgSCAWwEggFoAWYAdQCt9776fP8Q
        yIudPZwePhhqtGcpXc+xDCTKhYY069yCigAAAYHY940/AAAEAwBGMEQCIGoaF2yu
        Kt/Khw0cbiPyqhn3v0jm/eHnh6xdVUjBalJZAiAh4TfyJO8LuK/OxlygRO0Peff/
        TssYffdpAFpqiKaBXQB2AHoyjFTYty22IOo44FIe6YQWcDIThU070ivBOlejUutS
        AAABgdj3js8AAAQDAEcwRQIgfllgnFtIZqiGmn62U3QJ4u4vLEgqWMl/BgMjjJ/3
        aSoCIQCRc91z78/Hxl1GkWvQ1Or7UsyOYeNM9bxabC9BPvm9ugB1AOg+0No+9QY1
        MudXKLyJa8kD08vREWvs62nhd31tBr1uAAABgdj3jN8AAAQDAEYwRAIgS2oVos7y
        N5a0g/Jg/BP4QNnGoPGTvAQVMw1LymrbJwYCICq9dIn2INBOOaTUQjsljooyt9/L
        mzMbYiD/bXb850+pMA0GCSqGSIb3DQEBCwUAA4IBAQANfNQ+ffdu6WX2uv4e2nTP
        z66BKIl4rsTY/xSwHcVFCa/cIZiuSTJW3R69Umk88YZxEPbYpVOVsK4smLvULOrl
        j6oq0hhotPwfM6YsJVmQMg96MSUubhREMHR7YzrurVMOWBO4Hif5zvZhYXDHm9BV
        VKJJCVHMfSnc6AMLiBIHh2MxIEWfQKa/LNRhEceixwZcLkCV3N3ATq9pjJ1+W0HW
        AUMzLCumHyPbDAZpl+Ghlt0LxMcQJc5GDWu6Dc+Qv40NAqsgevahluHjjQPqnbFv
        qk8zAoQMXhweazd92gGlBUfPiXciYX13+VOLkcluzFAEDXtbGhsr86U+0isvfzak
        -----END CERTIFICATE-----

rw_groups: []
ro_groups: []
sync_groups: []

