---
###############################################################################
## Common configuration
###############################################################################
projects:
  development:
    ###############################################################################
    ## development Environment
    ###############################################################################
    enabled: true
    destination: https://kubernetes.default.svc
    apps:
      petclinic:
        enabled: true
        from_registry: true
        chart_path: petclinic
        repo_url: https://github.com/BoulderES/petclinic.git
        target_revision: main
        namespace: petclinic
        values_files:
          - values-development.yaml
