---
###############################################################################
## Common configuration
###############################################################################
projects:
  test:
    ###############################################################################
    ## development Environment
    ###############################################################################
    enabled: true
    destination: https://kubernetes.default.svc
    apps:
      dummy-apps-space:
        enabled: true
        from_registry: true
        chart_path: dummy-apps-space
        repo_url: https://github.com/BoulderES/petclinic.git
        target_revision: main
        namespace: dummy-apps-space
        values_files:
          - values-test.yaml
        syncPolicy:
          automated:
            prune: false
            selfHeal: true
